#!/bin/python

import os.path
import sys
import subprocess

#SRA_prefix_grabber take the imput list and returns seperate lists for control and treated for downstream DE anlysis
def sample_prefix_grabber(sample_list):
        #Check that the SRA_list path exists
        if os.path.exists(sample_list) == False:
                sys.exit("Please review the manual")
        else:
        #Open SRA_list file to obtain the SRA prefix for download
                with open(sample_list, 'r') as sample_file:
                        sample_data = []
                        for line in sample_file:
                                content_check = line.rstrip().split()
                                sample_data.append(content_check[0])
                        #Returns the sample prefix as an array
                        return(sample_data)
